package com.vickikbt.newsapp.util

object Constants {

    const val LICENSE_KEY="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnTg8ofAG93MkwYq3mIeh7NiYupjjdAza6npY/i6SFdCdMU/baVQIbPi4+YgQxqZMahmtnOI/8VpYfpk5IhuUSjy14Sg7df9aqsGDAQF4IVKDESQ74Bs3nMci4ukhLaQ2KktxLP0i38NDmvrbvff8hZeOVTDtdBxjnEuRFrWAqD+GfbsPS1zsKHqWYaE5TyrgCr3aMqeRaLtbbJFWtRubcC+uZ8b+mfVn+3vWHkGjF6lVj2dfoPAEINYL3eckYUn/e8tgd7XTgVe+FVcLuVIOFjulLepyqswvTuD3Pu+gfQlkkZ4vtFv1tndqIjrRKgrRwZMdfkPKz7glLOI8PZGS/wIDAQAB"

}